### ISSUE TITLE
运行demo时报错

### ISSUE THREAD

**Issue by fjibj** [Qihoo360/hbox#13]
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.hadoop.yarn.webapp.WebApps$Builder.build(Lorg/apache/hadoop/yarn/webapp/WebApp;)Lorg/apache/hadoop/yarn/webapp/WebApp;
	at net.qihoo.xlearning.AM.ApplicationWebService.start(ApplicationWebService.java:35)
	at org.apache.hadoop.service.CompositeService.serviceStart(CompositeService.java:120)
	at net.qihoo.xlearning.AM.ApplicationMaster.init(ApplicationMaster.java:217)
	at net.qihoo.xlearning.AM.ApplicationMaster.main(ApplicationMaster.java:1245)

**Comment by dailong** [comment]
这是hadoop 版本问题，2.6及以下没有build 方法
