### ISSUE TITLE
Tensorboard not show any info

### ISSUE THREAD

**Issue by lshmouse** [Qihoo360/hbox#63]
When running the tf example, there is no info in Tensorboard because of following exceptions.

The exception can be seen when changing the tensorboard stdout/err log from debug to INFO level.

```
19/02/01 16:13:41 INFO XLearningContainer: board: KeyError: None                                                             
19/02/01 16:13:41 INFO XLearningContainer: board: E0201 16:13:41.403089 140098737792768 _internal.py:88] Error on request:   
19/02/01 16:13:41 INFO XLearningContainer: board: Traceback (most recent call last):                                     
19/02/01 16:13:41 INFO XLearningContainer: board:   File "/usr/lib64/python2.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
19/02/01 16:13:41 INFO XLearningContainer: board:     execute(self.server.app)                                           
19/02/01 16:13:41 INFO XLearningContainer: board:   File "/usr/lib64/python2.7/site-packages/werkzeug/serving.py", line 258, in execute
19/02/01 16:13:41 INFO XLearningContainer: board:     application_iter = app(environ, start_response)                    
19/02/01 16:13:41 INFO XLearningContainer: board:   File "/usr/lib/python2.7/site-packages/tensorboard/backend/application.py", line 307, in __call__
19/02/01 16:13:41 INFO XLearningContainer: board:     return self.data_applications[clean_path](environ, start_response) 
19/02/01 16:13:41 INFO XLearningContainer: board:   File "/usr/lib64/python2.7/site-packages/werkzeug/wrappers.py", line 308, in application
19/02/01 16:13:41 INFO XLearningContainer: board:     resp = f(*args[:-2] + (request,))                                  
19/02/01 16:13:41 INFO XLearningContainer: board:   File "/usr/lib/python2.7/site-packages/tensorboard/plugins/scalar/scalars_plugin.py", line 199, in scalars_route
19/02/01 16:13:41 INFO XLearningContainer: board:     (body, mime_type) = self.scalars_impl(tag, run, experiment, output_format)
19/02/01 16:13:41 INFO XLearningContainer: board:   File "/usr/lib/python2.7/site-packages/tensorboard/plugins/scalar/scalars_plugin.py", line 157, in scalars_impl
19/02/01 16:13:41 INFO XLearningContainer: board:     tensor_events = self._multiplexer.Tensors(run, tag)                
19/02/01 16:13:41 INFO XLearningContainer: board:   File "/usr/lib/python2.7/site-packages/tensorboard/backend/event_processing/plugin_event_multiplexer.py", line 397, in Tensors
19/02/01 16:13:41 INFO XLearningContainer: board:     accumulator = self.GetAccumulator(run)                             
19/02/01 16:13:41 INFO XLearningContainer: board:   File "/usr/lib/python2.7/site-packages/tensorboard/backend/event_processing/plugin_event_multiplexer.py", line 473, in GetAccumulator
19/02/01 16:13:41 INFO XLearningContainer: board:     return self._accumulators[run]                                     
19/02/01 16:13:41 INFO XLearningContainer: board: KeyError: None 
```

**Comment by lshmouse** [comment]
Ref https://github.com/tensorflow/tensorboard/issues/1555.
Rolling back tf to version 1.10 will fix this problem
